import Head from 'next/head'
import { BiWorld } from 'react-icons/bi'
import { CgRowFirst } from 'react-icons/cg'
import { AiFillContainer } from 'react-icons/ai'
import { DiCssdeck } from 'react-icons/di'


import Canvas from '../components/layout/Canvas'
import SidebarNav from '../components/layout/SidebarNav'
import TopHeader from '../components/layout/TopHeader'
import Card from '../components/wrappers/Card'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* container */}
      <div className="flex h-screen">
        <SidebarNav />
        <div className='flex flex-col w-full'>
          <TopHeader />
          <Canvas>
            <div className='grid grid-cols-4 gap-4'>
              <Card>
                <div className='grid grid-col gap-2'>
                  <span className='uppercase text-xs text-gray-600'>AVERAGE SALES</span>
                  <span className='font-semibold'>$1,045.45</span>
                </div>
                <div className='bg-red-500 p-1 rounded-md'><BiWorld className=' text-white text-3xl' /></div>
              </Card>
              <Card>
                <div className='grid grid-col gap-2'>
                  <span className='uppercase text-xs text-gray-600'>AVERAGE SALES</span>
                  <span className='font-semibold'>$1,045.45</span>
                </div>
                <div className='bg-lime-500 p-1 rounded-md'><CgRowFirst className=' text-white text-3xl' /></div>
              </Card>
              <Card>
                <div className='grid grid-col gap-2'>
                  <span className='uppercase text-xs text-gray-600'>AVERAGE SALES</span>
                  <span className='font-semibold'>$1,045.45</span>
                </div>
                <div className='bg-blue-500 p-1 rounded-md'><AiFillContainer className=' text-white text-3xl' /></div>
              </Card>
              <Card>
                <div className='grid grid-col gap-2'>
                  <span className='uppercase text-xs text-gray-600'>AVERAGE SALES</span>
                  <span className='font-semibold'>$1,045.45</span>
                </div>
                <div className='bg-orange-500 p-1 rounded-md'><DiCssdeck className=' text-white text-3xl' /></div>
              </Card>
            </div>
          </Canvas>
        </div>
      </div>

    </div>
  )
}
